config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :meetups do
    resources :comments
  end
  root "meetups#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :meetups, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meetup, counter_cache: true
  belongs_to :user
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments

  before_create :generate_authentication_token

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  attr_accessor :current_user
  # disable the CSRF token
  protect_from_forgery with: :null_session

  # disable cookies (no set-cookies header in response)
  before_action :destroy_session

  # disable the CSRF token
  skip_before_action :verify_authenticity_token

  def destroy_session
    request.session_options[:skip] = true
  end

  def authenticate_user!
    token, options = ActionController::HttpAuthentication::Token.token_and_options(request)

    user_email = options.blank?? nil : options[:email]
    user = user_email && User.find_by(email: user_email)

    if user && ActiveSupport::SecurityUtils.secure_compare(user.authentication_token, token)
      self.current_user = user
    else
      return unauthenticated!
    end
  end

  def unauthenticated!
    api_error(status: 401)
  end

  def api_error(opts = {})
    render nothing: true, status: opts[:status]
  end  
end

app/controllers/api/v1/meetups_controller.rb
class Api::V1::MeetupsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @meetups = Meetup.all
  end  
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < ApplicationController
  def create
    @user = User.find_by(email: create_params[:email])
    if @user && @user.valid_password?(create_params[:password])
      sign_in :user, @user
    else
      return api_error(status: 401)
    end
  end

  private

  def create_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :authenticate_user!, only: [:update]
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(update_params)
  end

  private

  def update_params
    params.require(:user).permit(:name)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @meetup = Meetup.find(params[:meetup_id])

    @comment = Comment.new(comment_params)
    @comment.meetup_id = @meetup.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to :back
    else
      render :new
    end
  end

  protected
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]  
  def index
    @meetups = Meetup.all
  end

  def new
    @meetup = Meetup.new
  end

  def create
    @meetup = Meetup.new(meetup_params)
    @meetup.save
    redirect_to meetups_path
  end

  def show
    @meetup = Meetup.find(params[:id])
  end

  def edit
    @meetup = Meetup.find(params[:id])
  end

  def update
    @meetup = Meetup.find(params[:id])

    @meetup.update(meetup_params)

    redirect_to meetups_path, notice: "Update Success"
  end

  def destroy
    @meetup = Meetup.find(params[:id])
    @meetup.destroy
    flash[:alert] = "meetup deleted"
    redirect_to meetups_path
  end

  private

  def meetup_params
    params.require(:meetup).permit(:title, :description)
  end
end

app/helpers/api/v1/base_helper.rb
module Api::V1::BaseHelper
end

app/helpers/api/v1/meetups_helper.rb
module Api::V1::MeetupsHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Meetup</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to("登录", new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Hi!, <%= current_user.email %>
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                      <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetups/_comment_form.html.erb
<%= form_for(Comment.new, url: meetup_comments_path(@meetup)) do |f| %>
  <%= f.text_area :message %>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/meetups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑Meetup</h2>

    <hr>
    <%= form_for @meetup do |f| %>

    标题
    <%= f.text_field :title %>
    <br>
    叙述
    <br>
    <%= f.text_area :description %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

</div>

app/views/meetups/index.html.erb
<div class="col-md-12">
  <div class="meetup">
    <%= link_to("New meetup", new_meetup_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @meetups.each do |meetup| %>
        <tr>
          <td>#</td>
          <td><%= link_to(meetup.title, meetup_path(meetup)) %></td>
          <td><%= meetup.description %></td>
          <td>
              <%= link_to("Edit", edit_meetup_path(meetup), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", meetup_path(meetup),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/meetups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增meetup</h2>

    <hr>
    <%= form_for @meetup do |f| %>

    标题
    <%= f.text_field :title %>
    <br>
    叙述
    <br>
    <%= f.text_area :description %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

</div>

app/views/meetups/show.html.erb
<div class="col-md-12">
  <div class="meetup">
    <%= link_to("Edit", edit_meetup_path(@meetup), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @meetup.title %></h2>
  <p><%= @meetup.description %></p>
</div>
<% if @meetup.comments.empty? %>
  <p> 尚未有人留言 </p>
<% else %>
  <% @floor = 1 %>
  <% @meetup.comments.each do |comment| %>
    <%= @floor %>楼
    <div class="col-md-12">
      <p><%= comment.message %></p>
    </div>
    <% @floor = @floor + 1 %>
    </br>
  <% end%>
<% end %>


<%= render 'comment_form' %>